jobs:
    - job: Terraform_Terra_Scan
      displayName: Terrascan
      steps:
      - script: | 
          mkdir TerraScanReport
          docker pull accurics/terrascan
          docker run --rm --volume $(System.DefaultWorkingDirectory)/terraform/ --workdir / accurics/terrascan:latest scan --iac-type terraform --policy-type all --verbose --output xml > $(System.DefaultWorkingDirectory)/TerraScanReport/TerraScan-Report.xml
          docker run --rm --volume $(System.DefaultWorkingDirectory)/terraform/ --workdir / accurics/terrascan:latest scan --iac-type terraform --policy-type all --verbose
        displayName: 'Terrascan code Analyse'
      
      - script: |
          cd $(System.DefaultWorkingDirectory)/TerraScanReport
          ls -la
        displayName: 'Checking Directory'
        condition: always()
      
      # Delen van resultaten als artifact na de run.
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Terrascan Report'
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/TerraScanReport'
          ArtifactName: TerrascanReport

      - task: PublishTestResults@2
        displayName: Publish Terrascan Test Results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit' #Opties van formaat "JUnit, NUnit, VSTest, xUnit, cTest"
          testResultsFiles: '**/*TerraScan-Report.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/TerraScanReport'
          mergeTestResults: false
          testRunTitle: Terrascan Scan
          failTaskOnFailedTests: false
          publishRunAttachments: true